### ISSUE TITLE
KeyPromoter is out dated and doesn't work.

### ISSUE THREAD

**Issue by the-jedi-droid** [nisrulz/android-tips-tricks#6]
KeyPromoter is outdated and doesn't work on Android Studio anymore -- using AS 2.2 RC on OS X El Capitan. However, there is an active fork for the same - https://github.com/athiele/key-promoter-fork.

**Comment by nisrulz** [comment]
Is it ?  I am still on AS 2.1. Didnot know that. Will check the fork and update after I can verify it works. Thanks for pointing it out 😸

**Comment by nisrulz** [comment]
@suhas-sm I just tried it with AS 2.2 RC and it does not work. 

```
Plugin 'key promoter' is incompatible with this installation.
```

I am running Java 8, Android 2.2 RC1 everything updated. Downloaded the last stable release from the fork you referred.

On the contrary the original **Old** [plugin](https://plugins.jetbrains.com/plugin/1003) works perfectly with AS 2.1 and 2.2 RC1.
Downloaded the last version and tested it.

**Comment by the-jedi-droid** [comment]
@nisrulz Roger that. Fork is incompatible. But again I had installed last version of the original old plugin. And nothing really happened :| AS 2.2 RC. Is RC1 same as RC or have I missed out on this update. Will try again :/

**Comment by nisrulz** [comment]
They have released only one RC, hence RC1 here :) Just give it a try once more, it should work.
Close the issue if it does 😸

**Comment by the-jedi-droid** [comment]
It does work. I was checking wrong scenarios, I guess. Anyways, pretty awesome compilation. Love it !!
